[project]
name = "{{ cookiecutter.project_module_name }}"
version = "{{ cookiecutter.project_version }}"
description = "{{ cookiecutter.project_description }}"
readme = "README.md"
requires-python = ">={{ cookiecutter.python_version }}"
dependencies = []

[dependency-groups]
lint = [
    "ruff>=0.14.7",
    "ty",
    "pytest",
    "sphinx",
    "sphinx_rtd_theme",
    "numpy",
    "pandas",
    "opencv",
    "matplotlib",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.workspace]
members = ["{{ cookiecutter.project_slug }}/src"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/{{ cookiecutter.project_module_name }}"]
